# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!


service: serverless-chat

provider:
  name: aws
  runtime: python3.7
  websocketApiName: serverless-chat-api
  websocketApiRouteSelectionExpression: $request.body.action
  iamRoleStatements:
      - Effect: Allow
        Action:
            - "execute-api:ManageConnections"
        Resource:
            - "arn:aws:execute-api:*:*:**/@connections/*"

plugins:
    - serverless-python-requirements

custom:
    pythonRequirements:
        dockerizePip: true
        noDeploy: []

functions:
    connectionManager:
        handler: handler.connection_manager
        events:
            - websocket:
                route: $connect
            - websocket:
                route: $disconnect
    defaultMessage:
        handler: handler.default_message
        events:
            - websocket:
                route: $default
    getRecentMessages:
        handler: handler.get_recent_messages
        events:
            - websocket:
                route: getRecentMessages
    sendMessage:
        handler: handler.send_message
        events:
            - websocket:
                route: sendMessage
    ping:
        handler: handler.ping
        events:
            - http:
                path: ping
                method: get