# Generated by Django 2.2.3 on 2019-11-06 17:02

from django.db import migrations

def create_room(apps, schema_editor):
    Room = apps.get_model("data", "Room")
    Room(id=1, name='room1').save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_room),
    ]
